FROM rocker/shiny-verse:4.1.0
RUN apt-get update && apt-get upgrade -y && apt-get install -y  git-core libcurl4-openssl-dev libgit2-dev libicu-dev libssl-dev libxml2-dev make pandoc pandoc-citeproc pip python-is-python3 && rm -rf /var/lib/apt/lists/*
RUN echo "options(repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl')" >> /usr/local/lib/R/etc/Rprofile.site
# RUN R -e 'install.packages("remotes")'
# RUN R -e 'remotes::install_github("r-lib/remotes", ref = "97bbf81")'
# RUN Rscript -e 'remotes::install_version("htmltools",upgrade="never", version = "0.5.1.1")'
# RUN Rscript -e 'remotes::install_version("shiny",upgrade="never", version = "1.6.0")'
RUN Rscript -e 'remotes::install_version("config",upgrade="never", version = "0.3")'
# RUN Rscript -e 'remotes::install_version("dplyr",upgrade="never", version = "1.0.2")'
# RUN Rscript -e 'remotes::install_version("rmarkdown",upgrade="never", version = "2.7")'
RUN Rscript -e 'remotes::install_version("echarts4r",upgrade="never", version = "0.4.0")'
RUN Rscript -e 'remotes::install_version("reactable",upgrade="never", version = "0.2.3")'
# RUN Rscript -e 'remotes::install_version("readr",upgrade="never", version = "1.4.0")'
RUN Rscript -e 'remotes::install_version("golem",upgrade="never", version = "0.2.1")'
RUN pip install pandas argparse requests datetime
# RUN mkdir /build_zone
# ADD . /build_zone
# WORKDIR /build_zone
# RUN R -e 'remotes::install_local(upgrade="never")'
# EXPOSE 80
# CMD R -e "options('shiny.port'=80,shiny.host='0.0.0.0');intraday::run_app()"
