name: Test Runs
on:
  push:
    branches:
      - "prod"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Update packages
        run: |
          python -m pip install --upgrade pip
          pip install pandas argparse requests datetime
      - name: Run intraday
        run: |
          ls -la
          python intraday.pyc --rootkey ${{ secrets.ROOT_KEY }}
      - name: GitHub Push
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "Daily update"
          branch: "main"
